// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: base/room_state.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomState int32

const (
	RoomState_VOTING         RoomState = 0
	RoomState_SHOWING_RESULT RoomState = 1
)

// Enum value maps for RoomState.
var (
	RoomState_name = map[int32]string{
		0: "VOTING",
		1: "SHOWING_RESULT",
	}
	RoomState_value = map[string]int32{
		"VOTING":         0,
		"SHOWING_RESULT": 1,
	}
)

func (x RoomState) Enum() *RoomState {
	p := new(RoomState)
	*p = x
	return p
}

func (x RoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_base_room_state_proto_enumTypes[0].Descriptor()
}

func (RoomState) Type() protoreflect.EnumType {
	return &file_base_room_state_proto_enumTypes[0]
}

func (x RoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomState.Descriptor instead.
func (RoomState) EnumDescriptor() ([]byte, []int) {
	return file_base_room_state_proto_rawDescGZIP(), []int{0}
}

var File_base_room_state_proto protoreflect.FileDescriptor

var file_base_room_state_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2a, 0x2b, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x4f, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x48, 0x4f, 0x57, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10,
	0x01, 0x42, 0x2a, 0x5a, 0x28, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b,
	0x65, 0x72, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2f, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_room_state_proto_rawDescOnce sync.Once
	file_base_room_state_proto_rawDescData = file_base_room_state_proto_rawDesc
)

func file_base_room_state_proto_rawDescGZIP() []byte {
	file_base_room_state_proto_rawDescOnce.Do(func() {
		file_base_room_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_room_state_proto_rawDescData)
	})
	return file_base_room_state_proto_rawDescData
}

var file_base_room_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_base_room_state_proto_goTypes = []any{
	(RoomState)(0), // 0: planningpoker.realtime.base.RoomState
}
var file_base_room_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_room_state_proto_init() }
func file_base_room_state_proto_init() {
	if File_base_room_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_room_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_room_state_proto_goTypes,
		DependencyIndexes: file_base_room_state_proto_depIdxs,
		EnumInfos:         file_base_room_state_proto_enumTypes,
	}.Build()
	File_base_room_state_proto = out.File
	file_base_room_state_proto_rawDesc = nil
	file_base_room_state_proto_goTypes = nil
	file_base_room_state_proto_depIdxs = nil
}
