// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: base/voting_card_type.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VotingCardType int32

const (
	VotingCardType_FIBONACCI   VotingCardType = 0
	VotingCardType_SHIRT_SIZES VotingCardType = 1
)

// Enum value maps for VotingCardType.
var (
	VotingCardType_name = map[int32]string{
		0: "FIBONACCI",
		1: "SHIRT_SIZES",
	}
	VotingCardType_value = map[string]int32{
		"FIBONACCI":   0,
		"SHIRT_SIZES": 1,
	}
)

func (x VotingCardType) Enum() *VotingCardType {
	p := new(VotingCardType)
	*p = x
	return p
}

func (x VotingCardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VotingCardType) Descriptor() protoreflect.EnumDescriptor {
	return file_base_voting_card_type_proto_enumTypes[0].Descriptor()
}

func (VotingCardType) Type() protoreflect.EnumType {
	return &file_base_voting_card_type_proto_enumTypes[0]
}

func (x VotingCardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VotingCardType.Descriptor instead.
func (VotingCardType) EnumDescriptor() ([]byte, []int) {
	return file_base_voting_card_type_proto_rawDescGZIP(), []int{0}
}

var File_base_voting_card_type_proto protoreflect.FileDescriptor

var file_base_voting_card_type_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70,
	0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2a, 0x30, 0x0a, 0x0e, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x49, 0x42, 0x4f, 0x4e, 0x41, 0x43, 0x43, 0x49,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x48, 0x49, 0x52, 0x54, 0x5f, 0x53, 0x49, 0x5a, 0x45,
	0x53, 0x10, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70,
	0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_voting_card_type_proto_rawDescOnce sync.Once
	file_base_voting_card_type_proto_rawDescData = file_base_voting_card_type_proto_rawDesc
)

func file_base_voting_card_type_proto_rawDescGZIP() []byte {
	file_base_voting_card_type_proto_rawDescOnce.Do(func() {
		file_base_voting_card_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_voting_card_type_proto_rawDescData)
	})
	return file_base_voting_card_type_proto_rawDescData
}

var file_base_voting_card_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_base_voting_card_type_proto_goTypes = []any{
	(VotingCardType)(0), // 0: planningpoker.base.VotingCardType
}
var file_base_voting_card_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_voting_card_type_proto_init() }
func file_base_voting_card_type_proto_init() {
	if File_base_voting_card_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_voting_card_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_voting_card_type_proto_goTypes,
		DependencyIndexes: file_base_voting_card_type_proto_depIdxs,
		EnumInfos:         file_base_voting_card_type_proto_enumTypes,
	}.Build()
	File_base_voting_card_type_proto = out.File
	file_base_voting_card_type_proto_rawDesc = nil
	file_base_voting_card_type_proto_goTypes = nil
	file_base_voting_card_type_proto_depIdxs = nil
}
