version: 0.0
os: linux
files:
  - source: ./docker-compose.production.yml
    destination: /home/ec2-user/app
  - source: ./package.json
    destination: /home/ec2-user/app
  - source: ./package-lock.json
    destination: /home/ec2-user/app
  - source: ./.docker
    destination: /home/ec2-user/app/.docker
  - source: ./server
    destination: /home/ec2-user/app/server
  - source: ./shared
    destination: /home/ec2-user/app/shared
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - directory

  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - file
hooks:
  BeforeInstall:
    - location: .aws/scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: .aws/scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: .aws/scripts/application_start.sh
      timeout: 300
      runas: ec2-user
