version: 0.0
os: linux
files:
  - source: ./server
    destination: /home/ec2-user/my-planit-poker/server
  - source: ./shared
    destination: /home/ec2-user/my-planit-poker/shared
permissions:
  - object: /home/ec2-user/my-planit-poker
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - directory
  - object: /home/ec2-user/my-planit-poker
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
