services:
    frontend:
        build:
            context: .
            dockerfile: .docker/Dockerfile.frontend.dev
            args:
                - VITE_SESSION_SECRET=${VITE_SESSION_SECRET}
                - VITE_BACKEND_ENDPOINT=${VITE_BACKEND_ENDPOINT}
        env_file: ./packages/vote-client/.env
        volumes:
            - ./packages/vote-client/.react-router:/usr/src/app/packages/vote-client/.react-router
        ports:
            - 24678:24678
        develop:
            watch:
                - action: rebuild
                  path: package.json
                - action: rebuild
                  path: ./packages/vote-client/package.json
                - action: sync+restart
                  path: ./packages/vote-client/server.js
                  target: /usr/src/app/packages/vote-client/server.js
                - action: sync
                  path: ./packages/vote-client
                  target: /usr/src/app/packages/vote-client
                  ignore:
                      - build
                      - package.json
                      - server.js
                      - .react-router

    realtime:
        build:
            context: ./packages/vote-realtime
            dockerfile: ../../.docker/Dockerfile.realtime
        working_dir: /usr/src/app
        entrypoint: ['/bin/sh', '-c']
        volumes:
            - pb_data:/usr/src/app/pb_data
            - ./packages/vote-realtime/migrations:/usr/src/app/migrations
        command:
            - |
                pocketbase superuser upsert realtime@realtime.com realtime
                pocketbase serve --http 0.0.0.0:8090 --dev
        develop:
            watch:
                - action: rebuild
                  path: ./packages/vote-realtime
                  target: /usr/src/app
                  ignore:
                      - migrations

    proxy:
        image: caddy:2.8
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        develop:
            watch:
                - action: sync+restart
                  path: ./.docker/caddy/conf
                  target: /etc/caddy

volumes:
    caddy_data:
    caddy_config:
    pb_data:
