services:
    frontend:
        build:
            context: .
            dockerfile: .docker/Dockerfile.frontend.dev
        develop:
            watch:
                - action: sync
                  path: ./packages/vote-client
                  target: /usr/src/app/packages/vote-client
        environment:
            - BACKEND_ENDPOINT=http://backend:3000/api

    realtime:
        build:
            context: ./packages/vote-realtime
            dockerfile: ../../.docker/Dockerfile.realtime
        working_dir: /usr/src/app
        entrypoint: ['/bin/sh', '-c']
        volumes:
            - pb_data:/usr/src/app/pb_data
        command:
            - |
                pocketbase superuser upsert realtime@realtime.com realtime
                pocketbase serve --http 0.0.0.0:8090
        develop:
            watch:
                - action: rebuild
                  path: ./packages/vote-realtime
                  target: /usr/src/app

    proxy:
        image: caddy:2.8
        volumes:
            - ./.docker/caddy/conf:/etc/caddy
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        depends_on:
            - frontend
            - realtime

volumes:
    caddy_data:
    caddy_config:
    pb_data:
