version: '3'

services:
  app:
    ports:
      - "3001:5173"
      - "3000:3000"
    working_dir: /home/node/app
    user: "node"
    command: >
      sh -c "
        npm run dev --workspace=client -- --host 0.0.0.0 --port 5173 &
          npm run dev --workspace=server
      "
    volumes:
      - ./:/home/node/app
    image: "node:lts-slim"
