// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: room_state_broadcast.proto

package dist_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	base "planningpoker/domain_models/dist_go/base"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomStateBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    base.RoomState `protobuf:"varint,1,opt,name=state,proto3,enum=planningpoker.realtime.base.RoomState" json:"state,omitempty"`
	CardType base.CardType  `protobuf:"varint,2,opt,name=cardType,proto3,enum=planningpoker.realtime.base.CardType" json:"cardType,omitempty"`
}

func (x *RoomStateBroadcast) Reset() {
	*x = RoomStateBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_state_broadcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStateBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateBroadcast) ProtoMessage() {}

func (x *RoomStateBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_room_state_broadcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateBroadcast.ProtoReflect.Descriptor instead.
func (*RoomStateBroadcast) Descriptor() ([]byte, []int) {
	return file_room_state_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *RoomStateBroadcast) GetState() base.RoomState {
	if x != nil {
		return x.State
	}
	return base.RoomState(0)
}

func (x *RoomStateBroadcast) GetCardType() base.CardType {
	if x != nil {
		return x.CardType
	}
	return base.CardType(0)
}

var File_room_state_broadcast_proto protoreflect.FileDescriptor

var file_room_state_broadcast_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x6c,
	0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x61, 0x6c,
	0x74, 0x69, 0x6d, 0x65, 0x1a, 0x15, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x63, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x70, 0x6c, 0x61,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x2d, 0x67, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_state_broadcast_proto_rawDescOnce sync.Once
	file_room_state_broadcast_proto_rawDescData = file_room_state_broadcast_proto_rawDesc
)

func file_room_state_broadcast_proto_rawDescGZIP() []byte {
	file_room_state_broadcast_proto_rawDescOnce.Do(func() {
		file_room_state_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_state_broadcast_proto_rawDescData)
	})
	return file_room_state_broadcast_proto_rawDescData
}

var file_room_state_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_room_state_broadcast_proto_goTypes = []any{
	(*RoomStateBroadcast)(nil), // 0: planningpoker.realtime.RoomStateBroadcast
	(base.RoomState)(0),        // 1: planningpoker.realtime.base.RoomState
	(base.CardType)(0),         // 2: planningpoker.realtime.base.CardType
}
var file_room_state_broadcast_proto_depIdxs = []int32{
	1, // 0: planningpoker.realtime.RoomStateBroadcast.state:type_name -> planningpoker.realtime.base.RoomState
	2, // 1: planningpoker.realtime.RoomStateBroadcast.cardType:type_name -> planningpoker.realtime.base.CardType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_state_broadcast_proto_init() }
func file_room_state_broadcast_proto_init() {
	if File_room_state_broadcast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_state_broadcast_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RoomStateBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_state_broadcast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_state_broadcast_proto_goTypes,
		DependencyIndexes: file_room_state_broadcast_proto_depIdxs,
		MessageInfos:      file_room_state_broadcast_proto_msgTypes,
	}.Build()
	File_room_state_broadcast_proto = out.File
	file_room_state_broadcast_proto_rawDesc = nil
	file_room_state_broadcast_proto_goTypes = nil
	file_room_state_broadcast_proto_depIdxs = nil
}
