// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: session/session_response.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Session *Session               `protobuf:"bytes,1,opt,name=session"`
	xxx_hidden_Token   *Token                 `protobuf:"bytes,2,opt,name=token"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_session_session_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionResponse) GetSession() *Session {
	if x != nil {
		return x.xxx_hidden_Session
	}
	return nil
}

func (x *SessionResponse) GetToken() *Token {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *SessionResponse) SetSession(v *Session) {
	x.xxx_hidden_Session = v
}

func (x *SessionResponse) SetToken(v *Token) {
	x.xxx_hidden_Token = v
}

func (x *SessionResponse) HasSession() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Session != nil
}

func (x *SessionResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *SessionResponse) ClearSession() {
	x.xxx_hidden_Session = nil
}

func (x *SessionResponse) ClearToken() {
	x.xxx_hidden_Token = nil
}

type SessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Session *Session
	Token   *Token
}

func (b0 SessionResponse_builder) Build() *SessionResponse {
	m0 := &SessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Session = b.Session
	x.xxx_hidden_Token = b.Token
	return m0
}

var File_session_session_response_proto protoreflect.FileDescriptor

const file_session_session_response_proto_rawDesc = "" +
	"\n" +
	"\x1esession/session_response.proto\x12\asession\x1a\x15session/session.proto\x1a\x13session/token.proto\"c\n" +
	"\x0fSessionResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.session.SessionR\asession\x12$\n" +
	"\x05token\x18\x02 \x01(\v2\x0e.session.TokenR\x05tokenB'Z%github.com/joelson-c/votecoms/sessionb\beditionsp\xe8\a"

var file_session_session_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_session_session_response_proto_goTypes = []any{
	(*SessionResponse)(nil), // 0: session.SessionResponse
	(*Session)(nil),         // 1: session.Session
	(*Token)(nil),           // 2: session.Token
}
var file_session_session_response_proto_depIdxs = []int32{
	1, // 0: session.SessionResponse.session:type_name -> session.Session
	2, // 1: session.SessionResponse.token:type_name -> session.Token
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_session_session_response_proto_init() }
func file_session_session_response_proto_init() {
	if File_session_session_response_proto != nil {
		return
	}
	file_session_session_proto_init()
	file_session_token_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_session_response_proto_rawDesc), len(file_session_session_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_session_response_proto_goTypes,
		DependencyIndexes: file_session_session_response_proto_depIdxs,
		MessageInfos:      file_session_session_response_proto_msgTypes,
	}.Build()
	File_session_session_response_proto = out.File
	file_session_session_response_proto_goTypes = nil
	file_session_session_response_proto_depIdxs = nil
}
