// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/card_type.proto (package planningpoker.realtime.base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file base/card_type.proto.
 */
export const file_base_card_type: GenFile = /*@__PURE__*/
  fileDesc("ChRiYXNlL2NhcmRfdHlwZS5wcm90bxIbcGxhbm5pbmdwb2tlci5yZWFsdGltZS5iYXNlKioKCENhcmRUeXBlEg0KCUZJQk9OQUNDSRAAEg8KC1NISVJUX1NJWkVTEAFCKloocGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2Rpc3RfZ28vYmFzZWIGcHJvdG8z");

/**
 * @generated from enum planningpoker.realtime.base.CardType
 */
export enum CardType {
  /**
   * @generated from enum value: FIBONACCI = 0;
   */
  FIBONACCI = 0,

  /**
   * @generated from enum value: SHIRT_SIZES = 1;
   */
  SHIRT_SIZES = 1,
}

/**
 * Describes the enum planningpoker.realtime.base.CardType.
 */
export const CardTypeSchema: GenEnum<CardType> = /*@__PURE__*/
  enumDesc(file_base_card_type, 0);

