// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/error.proto (package planningpoker.base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/error.proto.
 */
export const file_base_error: GenFile = /*@__PURE__*/
  fileDesc("ChBiYXNlL2Vycm9yLnByb3RvEhJwbGFubmluZ3Bva2VyLmJhc2UiJQoFRXJyb3ISDgoGcmVhc29uGAEgASgJEgwKBGNvZGUYAiABKAlCKVoncGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2RvbWFpbi9iYXNlYgZwcm90bzM");

/**
 * @generated from message planningpoker.base.Error
 */
export type Error = Message<"planningpoker.base.Error"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message planningpoker.base.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_base_error, 0);

