// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/message_type.proto (package planningpoker.realtime.base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file base/message_type.proto.
 */
export const file_base_message_type: GenFile = /*@__PURE__*/
  fileDesc("ChdiYXNlL21lc3NhZ2VfdHlwZS5wcm90bxIbcGxhbm5pbmdwb2tlci5yZWFsdGltZS5iYXNlKroBCgtNZXNzYWdlVHlwZRIJCgVFUlJPUhAAEhcKE0NSRUFURV9ST09NX1JFUVVFU1QQARIYChRDUkVBVEVfUk9PTV9SRVNQT05TRRACEhUKEUpPSU5fUk9PTV9SRVFVRVNUEAMSFgoSSk9JTl9ST09NX1JFU1BPTlNFEAQSEAoMVk9URV9SRVFVRVNUEAUSEgoOVk9URV9CUk9BRENBU1QQBhIYChRST09NX1NUQVRFX0JST0FEQ0FTVBAHQipaKHBsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kaXN0X2dvL2Jhc2ViBnByb3RvMw");

/**
 * @generated from enum planningpoker.realtime.base.MessageType
 */
export enum MessageType {
  /**
   * @generated from enum value: ERROR = 0;
   */
  ERROR = 0,

  /**
   * @generated from enum value: CREATE_ROOM_REQUEST = 1;
   */
  CREATE_ROOM_REQUEST = 1,

  /**
   * @generated from enum value: CREATE_ROOM_RESPONSE = 2;
   */
  CREATE_ROOM_RESPONSE = 2,

  /**
   * @generated from enum value: JOIN_ROOM_REQUEST = 3;
   */
  JOIN_ROOM_REQUEST = 3,

  /**
   * @generated from enum value: JOIN_ROOM_RESPONSE = 4;
   */
  JOIN_ROOM_RESPONSE = 4,

  /**
   * @generated from enum value: VOTE_REQUEST = 5;
   */
  VOTE_REQUEST = 5,

  /**
   * @generated from enum value: VOTE_BROADCAST = 6;
   */
  VOTE_BROADCAST = 6,

  /**
   * @generated from enum value: ROOM_STATE_BROADCAST = 7;
   */
  ROOM_STATE_BROADCAST = 7,
}

/**
 * Describes the enum planningpoker.realtime.base.MessageType.
 */
export const MessageTypeSchema: GenEnum<MessageType> = /*@__PURE__*/
  enumDesc(file_base_message_type, 0);

