// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/room_state.proto (package planningpoker.realtime.base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file base/room_state.proto.
 */
export const file_base_room_state: GenFile = /*@__PURE__*/
  fileDesc("ChViYXNlL3Jvb21fc3RhdGUucHJvdG8SG3BsYW5uaW5ncG9rZXIucmVhbHRpbWUuYmFzZSorCglSb29tU3RhdGUSCgoGVk9USU5HEAASEgoOU0hPV0lOR19SRVNVTFQQAUIqWihwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZGlzdF9nby9iYXNlYgZwcm90bzM");

/**
 * @generated from enum planningpoker.realtime.base.RoomState
 */
export enum RoomState {
  /**
   * @generated from enum value: VOTING = 0;
   */
  VOTING = 0,

  /**
   * @generated from enum value: SHOWING_RESULT = 1;
   */
  SHOWING_RESULT = 1,
}

/**
 * Describes the enum planningpoker.realtime.base.RoomState.
 */
export const RoomStateSchema: GenEnum<RoomState> = /*@__PURE__*/
  enumDesc(file_base_room_state, 0);

