// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/voting_card.proto (package planningpoker.base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/voting_card.proto.
 */
export const file_base_voting_card: GenFile = /*@__PURE__*/
  fileDesc("ChZiYXNlL3ZvdGluZ19jYXJkLnByb3RvEhJwbGFubmluZ3Bva2VyLmJhc2UiGwoKVm90aW5nQ2FyZBINCgV2YWx1ZRgBIAEoCUIpWidwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZG9tYWluL2Jhc2ViBnByb3RvMw");

/**
 * @generated from message planningpoker.base.VotingCard
 */
export type VotingCard = Message<"planningpoker.base.VotingCard"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message planningpoker.base.VotingCard.
 * Use `create(VotingCardSchema)` to create a new message.
 */
export const VotingCardSchema: GenMessage<VotingCard> = /*@__PURE__*/
  messageDesc(file_base_voting_card, 0);

