// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/voting_room.proto (package planningpoker.base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingCardType } from "./voting_card_type_pb";
import { file_base_voting_card_type } from "./voting_card_type_pb";
import type { VotingRoomState } from "./voting_room_state_pb";
import { file_base_voting_room_state } from "./voting_room_state_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/voting_room.proto.
 */
export const file_base_voting_room: GenFile = /*@__PURE__*/
  fileDesc("ChZiYXNlL3ZvdGluZ19yb29tLnByb3RvEhJwbGFubmluZ3Bva2VyLmJhc2UihgEKClZvdGluZ1Jvb20SDgoGcm9vbUlkGAEgASgJEjQKCGNhcmRUeXBlGAIgASgOMiIucGxhbm5pbmdwb2tlci5iYXNlLlZvdGluZ0NhcmRUeXBlEjIKBXN0YXRlGAMgASgOMiMucGxhbm5pbmdwb2tlci5iYXNlLlZvdGluZ1Jvb21TdGF0ZUIpWidwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZG9tYWluL2Jhc2ViBnByb3RvMw", [file_base_voting_card_type, file_base_voting_room_state]);

/**
 * @generated from message planningpoker.base.VotingRoom
 */
export type VotingRoom = Message<"planningpoker.base.VotingRoom"> & {
  /**
   * @generated from field: string roomId = 1;
   */
  roomId: string;

  /**
   * @generated from field: planningpoker.base.VotingCardType cardType = 2;
   */
  cardType: VotingCardType;

  /**
   * @generated from field: planningpoker.base.VotingRoomState state = 3;
   */
  state: VotingRoomState;
};

/**
 * Describes the message planningpoker.base.VotingRoom.
 * Use `create(VotingRoomSchema)` to create a new message.
 */
export const VotingRoomSchema: GenMessage<VotingRoom> = /*@__PURE__*/
  messageDesc(file_base_voting_room, 0);

