// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/voting_room_state.proto (package planningpoker.base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file base/voting_room_state.proto.
 */
export const file_base_voting_room_state: GenFile = /*@__PURE__*/
  fileDesc("ChxiYXNlL3ZvdGluZ19yb29tX3N0YXRlLnByb3RvEhJwbGFubmluZ3Bva2VyLmJhc2UqMQoPVm90aW5nUm9vbVN0YXRlEgoKBlZPVElORxAAEhIKDlNIT1dJTkdfUkVTVUxUEAFCKVoncGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2RvbWFpbi9iYXNlYgZwcm90bzM");

/**
 * @generated from enum planningpoker.base.VotingRoomState
 */
export enum VotingRoomState {
  /**
   * @generated from enum value: VOTING = 0;
   */
  VOTING = 0,

  /**
   * @generated from enum value: SHOWING_RESULT = 1;
   */
  SHOWING_RESULT = 1,
}

/**
 * Describes the enum planningpoker.base.VotingRoomState.
 */
export const VotingRoomStateSchema: GenEnum<VotingRoomState> = /*@__PURE__*/
  enumDesc(file_base_voting_room_state, 0);

