// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/voting_card_type.proto (package planningpoker.base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file base/voting_card_type.proto.
 */
export const file_base_voting_card_type: GenFile = /*@__PURE__*/
  fileDesc("ChtiYXNlL3ZvdGluZ19jYXJkX3R5cGUucHJvdG8SEnBsYW5uaW5ncG9rZXIuYmFzZSowCg5Wb3RpbmdDYXJkVHlwZRINCglGSUJPTkFDQ0kQABIPCgtTSElSVF9TSVpFUxABQilaJ3BsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kb21haW4vYmFzZWIGcHJvdG8z");

/**
 * @generated from enum planningpoker.base.VotingCardType
 */
export enum VotingCardType {
  /**
   * @generated from enum value: FIBONACCI = 0;
   */
  FIBONACCI = 0,

  /**
   * @generated from enum value: SHIRT_SIZES = 1;
   */
  SHIRT_SIZES = 1,
}

/**
 * Describes the enum planningpoker.base.VotingCardType.
 */
export const VotingCardTypeSchema: GenEnum<VotingCardType> = /*@__PURE__*/
  enumDesc(file_base_voting_card_type, 0);

