// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file base/voting_user.proto (package planningpoker.base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingCard } from "./voting_card_pb";
import { file_base_voting_card } from "./voting_card_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/voting_user.proto.
 */
export const file_base_voting_user: GenFile = /*@__PURE__*/
  fileDesc("ChZiYXNlL3ZvdGluZ191c2VyLnByb3RvEhJwbGFubmluZ3Bva2VyLmJhc2Ui6QEKClZvdGluZ1VzZXISFAoMY29ubmVjdGlvbklkGAEgASgJEg4KBnJvb21JZBgCIAEoCRIQCghuaWNrbmFtZRgDIAEoCRIxCgR2b3RlGAQgASgLMh4ucGxhbm5pbmdwb2tlci5iYXNlLlZvdGluZ0NhcmRIAIgBARI1CghoYXNWb3RlZBgFIAEoCzIeLnBsYW5uaW5ncG9rZXIuYmFzZS5Wb3RpbmdDYXJkSAGIAQESDwoHaXNBZG1pbhgGIAEoCBISCgppc09ic2VydmVyGAcgASgIQgcKBV92b3RlQgsKCV9oYXNWb3RlZEIpWidwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZG9tYWluL2Jhc2ViBnByb3RvMw", [file_base_voting_card]);

/**
 * @generated from message planningpoker.base.VotingUser
 */
export type VotingUser = Message<"planningpoker.base.VotingUser"> & {
  /**
   * @generated from field: string connectionId = 1;
   */
  connectionId: string;

  /**
   * @generated from field: string roomId = 2;
   */
  roomId: string;

  /**
   * @generated from field: string nickname = 3;
   */
  nickname: string;

  /**
   * @generated from field: optional planningpoker.base.VotingCard vote = 4;
   */
  vote?: VotingCard;

  /**
   * @generated from field: optional planningpoker.base.VotingCard hasVoted = 5;
   */
  hasVoted?: VotingCard;

  /**
   * @generated from field: bool isAdmin = 6;
   */
  isAdmin: boolean;

  /**
   * @generated from field: bool isObserver = 7;
   */
  isObserver: boolean;
};

/**
 * Describes the message planningpoker.base.VotingUser.
 * Use `create(VotingUserSchema)` to create a new message.
 */
export const VotingUserSchema: GenMessage<VotingUser> = /*@__PURE__*/
  messageDesc(file_base_voting_user, 0);

