// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file create_room_response.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingRoom } from "./base/voting_room_pb";
import { file_base_voting_room } from "./base/voting_room_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file create_room_response.proto.
 */
export const file_create_room_response: GenFile = /*@__PURE__*/
  fileDesc("ChpjcmVhdGVfcm9vbV9yZXNwb25zZS5wcm90bxINcGxhbm5pbmdwb2tlciJCChJDcmVhdGVSb29tUmVzcG9uc2USLAoEcm9vbRgBIAEoCzIeLnBsYW5uaW5ncG9rZXIuYmFzZS5Wb3RpbmdSb29tQiRaInBsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kb21haW5iBnByb3RvMw", [file_base_voting_room]);

/**
 * @generated from message planningpoker.CreateRoomResponse
 */
export type CreateRoomResponse = Message<"planningpoker.CreateRoomResponse"> & {
  /**
   * @generated from field: planningpoker.base.VotingRoom room = 1;
   */
  room?: VotingRoom;
};

/**
 * Describes the message planningpoker.CreateRoomResponse.
 * Use `create(CreateRoomResponseSchema)` to create a new message.
 */
export const CreateRoomResponseSchema: GenMessage<CreateRoomResponse> = /*@__PURE__*/
  messageDesc(file_create_room_response, 0);

