// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file create_room_request.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file create_room_request.proto.
 */
export const file_create_room_request: GenFile = /*@__PURE__*/
  fileDesc("ChljcmVhdGVfcm9vbV9yZXF1ZXN0LnByb3RvEg1wbGFubmluZ3Bva2VyIhMKEUNyZWF0ZVJvb21SZXF1ZXN0QiRaInBsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kb21haW5iBnByb3RvMw");

/**
 * TBD
 *
 * @generated from message planningpoker.CreateRoomRequest
 */
export type CreateRoomRequest = Message<"planningpoker.CreateRoomRequest"> & {
};

/**
 * Describes the message planningpoker.CreateRoomRequest.
 * Use `create(CreateRoomRequestSchema)` to create a new message.
 */
export const CreateRoomRequestSchema: GenMessage<CreateRoomRequest> = /*@__PURE__*/
  messageDesc(file_create_room_request, 0);

