// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file create_room_request.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file create_room_request.proto.
 */
export const file_create_room_request: GenFile = /*@__PURE__*/
  fileDesc("ChljcmVhdGVfcm9vbV9yZXF1ZXN0LnByb3RvEhZwbGFubmluZ3Bva2VyLnJlYWx0aW1lIhMKEUNyZWF0ZVJvb21SZXF1ZXN0QiVaI3BsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kaXN0LWdvYgZwcm90bzM");

/**
 * TBD
 *
 * @generated from message planningpoker.realtime.CreateRoomRequest
 */
export type CreateRoomRequest = Message<"planningpoker.realtime.CreateRoomRequest"> & {
};

/**
 * Describes the message planningpoker.realtime.CreateRoomRequest.
 * Use `create(CreateRoomRequestSchema)` to create a new message.
 */
export const CreateRoomRequestSchema: GenMessage<CreateRoomRequest> = /*@__PURE__*/
  messageDesc(file_create_room_request, 0);

