// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file create_room_response.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file create_room_response.proto.
 */
export const file_create_room_response: GenFile = /*@__PURE__*/
  fileDesc("ChpjcmVhdGVfcm9vbV9yZXNwb25zZS5wcm90bxIWcGxhbm5pbmdwb2tlci5yZWFsdGltZSIkChJDcmVhdGVSb29tUmVzcG9uc2USDgoGcm9vbUlkGAEgASgJQiVaI3BsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kaXN0LWdvYgZwcm90bzM");

/**
 * @generated from message planningpoker.realtime.CreateRoomResponse
 */
export type CreateRoomResponse = Message<"planningpoker.realtime.CreateRoomResponse"> & {
  /**
   * @generated from field: string roomId = 1;
   */
  roomId: string;
};

/**
 * Describes the message planningpoker.realtime.CreateRoomResponse.
 * Use `create(CreateRoomResponseSchema)` to create a new message.
 */
export const CreateRoomResponseSchema: GenMessage<CreateRoomResponse> = /*@__PURE__*/
  messageDesc(file_create_room_response, 0);

