// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file error.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file error.proto.
 */
export const file_error: GenFile = /*@__PURE__*/
  fileDesc("CgtlcnJvci5wcm90bxIWcGxhbm5pbmdwb2tlci5yZWFsdGltZSIlCgVFcnJvchIOCgZyZWFzb24YASABKAkSDAoEY29kZRgCIAEoCUIlWiNwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZGlzdC1nb2IGcHJvdG8z");

/**
 * @generated from message planningpoker.realtime.Error
 */
export type Error = Message<"planningpoker.realtime.Error"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message planningpoker.realtime.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_error, 0);

