// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file join_room_response.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingRoom } from "./base/voting_room_pb";
import { file_base_voting_room } from "./base/voting_room_pb";
import type { VotingUser } from "./base/voting_user_pb";
import { file_base_voting_user } from "./base/voting_user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file join_room_response.proto.
 */
export const file_join_room_response: GenFile = /*@__PURE__*/
  fileDesc("Chhqb2luX3Jvb21fcmVzcG9uc2UucHJvdG8SDXBsYW5uaW5ncG9rZXIibgoQSm9pblJvb21SZXNwb25zZRIsCgRyb29tGAEgASgLMh4ucGxhbm5pbmdwb2tlci5iYXNlLlZvdGluZ1Jvb20SLAoEdXNlchgCIAEoCzIeLnBsYW5uaW5ncG9rZXIuYmFzZS5Wb3RpbmdVc2VyQiRaInBsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kb21haW5iBnByb3RvMw", [file_base_voting_room, file_base_voting_user]);

/**
 * @generated from message planningpoker.JoinRoomResponse
 */
export type JoinRoomResponse = Message<"planningpoker.JoinRoomResponse"> & {
  /**
   * @generated from field: planningpoker.base.VotingRoom room = 1;
   */
  room?: VotingRoom;

  /**
   * @generated from field: planningpoker.base.VotingUser user = 2;
   */
  user?: VotingUser;
};

/**
 * Describes the message planningpoker.JoinRoomResponse.
 * Use `create(JoinRoomResponseSchema)` to create a new message.
 */
export const JoinRoomResponseSchema: GenMessage<JoinRoomResponse> = /*@__PURE__*/
  messageDesc(file_join_room_response, 0);

