// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file join_room_request.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file join_room_request.proto.
 */
export const file_join_room_request: GenFile = /*@__PURE__*/
  fileDesc("Chdqb2luX3Jvb21fcmVxdWVzdC5wcm90bxINcGxhbm5pbmdwb2tlciJHCg9Kb2luUm9vbVJlcXVlc3QSDgoGcm9vbUlkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJEhIKCmlzT2JzZXJ2ZXIYAyABKAhCJFoicGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2RvbWFpbmIGcHJvdG8z");

/**
 * @generated from message planningpoker.JoinRoomRequest
 */
export type JoinRoomRequest = Message<"planningpoker.JoinRoomRequest"> & {
  /**
   * @generated from field: string roomId = 1;
   */
  roomId: string;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname: string;

  /**
   * @generated from field: bool isObserver = 3;
   */
  isObserver: boolean;
};

/**
 * Describes the message planningpoker.JoinRoomRequest.
 * Use `create(JoinRoomRequestSchema)` to create a new message.
 */
export const JoinRoomRequestSchema: GenMessage<JoinRoomRequest> = /*@__PURE__*/
  messageDesc(file_join_room_request, 0);

