// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file join_room_request.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file join_room_request.proto.
 */
export const file_join_room_request: GenFile = /*@__PURE__*/
  fileDesc("Chdqb2luX3Jvb21fcmVxdWVzdC5wcm90bxIWcGxhbm5pbmdwb2tlci5yZWFsdGltZSJHCg9Kb2luUm9vbVJlcXVlc3QSDgoGcm9vbUlkGAIgASgJEhAKCG5pY2tuYW1lGAMgASgJEhIKCmlzT2JzZXJ2ZXIYBCABKAhCJVojcGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2Rpc3QtZ29iBnByb3RvMw");

/**
 * @generated from message planningpoker.realtime.JoinRoomRequest
 */
export type JoinRoomRequest = Message<"planningpoker.realtime.JoinRoomRequest"> & {
  /**
   * @generated from field: string roomId = 2;
   */
  roomId: string;

  /**
   * @generated from field: string nickname = 3;
   */
  nickname: string;

  /**
   * @generated from field: bool isObserver = 4;
   */
  isObserver: boolean;
};

/**
 * Describes the message planningpoker.realtime.JoinRoomRequest.
 * Use `create(JoinRoomRequestSchema)` to create a new message.
 */
export const JoinRoomRequestSchema: GenMessage<JoinRoomRequest> = /*@__PURE__*/
  messageDesc(file_join_room_request, 0);

