// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file room_state_broadcast.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { RoomState } from "./base/room_state_pb";
import { file_base_room_state } from "./base/room_state_pb";
import type { CardType } from "./base/card_type_pb";
import { file_base_card_type } from "./base/card_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file room_state_broadcast.proto.
 */
export const file_room_state_broadcast: GenFile = /*@__PURE__*/
  fileDesc("Chpyb29tX3N0YXRlX2Jyb2FkY2FzdC5wcm90bxIWcGxhbm5pbmdwb2tlci5yZWFsdGltZSKEAQoSUm9vbVN0YXRlQnJvYWRjYXN0EjUKBXN0YXRlGAEgASgOMiYucGxhbm5pbmdwb2tlci5yZWFsdGltZS5iYXNlLlJvb21TdGF0ZRI3CghjYXJkVHlwZRgCIAEoDjIlLnBsYW5uaW5ncG9rZXIucmVhbHRpbWUuYmFzZS5DYXJkVHlwZUIlWiNwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZGlzdC1nb2IGcHJvdG8z", [file_base_room_state, file_base_card_type]);

/**
 * @generated from message planningpoker.realtime.RoomStateBroadcast
 */
export type RoomStateBroadcast = Message<"planningpoker.realtime.RoomStateBroadcast"> & {
  /**
   * @generated from field: planningpoker.realtime.base.RoomState state = 1;
   */
  state: RoomState;

  /**
   * @generated from field: planningpoker.realtime.base.CardType cardType = 2;
   */
  cardType: CardType;
};

/**
 * Describes the message planningpoker.realtime.RoomStateBroadcast.
 * Use `create(RoomStateBroadcastSchema)` to create a new message.
 */
export const RoomStateBroadcastSchema: GenMessage<RoomStateBroadcast> = /*@__PURE__*/
  messageDesc(file_room_state_broadcast, 0);

