// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file room_update_broadcast.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingRoom } from "./base/voting_room_pb";
import { file_base_voting_room } from "./base/voting_room_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file room_update_broadcast.proto.
 */
export const file_room_update_broadcast: GenFile = /*@__PURE__*/
  fileDesc("Chtyb29tX3VwZGF0ZV9icm9hZGNhc3QucHJvdG8SDXBsYW5uaW5ncG9rZXIiQwoTUm9vbVVwZGF0ZUJyb2FkY2FzdBIsCgRyb29tGAEgASgLMh4ucGxhbm5pbmdwb2tlci5iYXNlLlZvdGluZ1Jvb21CJFoicGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2RvbWFpbmIGcHJvdG8z", [file_base_voting_room]);

/**
 * @generated from message planningpoker.RoomUpdateBroadcast
 */
export type RoomUpdateBroadcast = Message<"planningpoker.RoomUpdateBroadcast"> & {
  /**
   * @generated from field: planningpoker.base.VotingRoom room = 1;
   */
  room?: VotingRoom;
};

/**
 * Describes the message planningpoker.RoomUpdateBroadcast.
 * Use `create(RoomUpdateBroadcastSchema)` to create a new message.
 */
export const RoomUpdateBroadcastSchema: GenMessage<RoomUpdateBroadcast> = /*@__PURE__*/
  messageDesc(file_room_update_broadcast, 0);

