// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file socket_message.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { CreateRoomRequest } from "./create_room_request_pb";
import { file_create_room_request } from "./create_room_request_pb";
import type { CreateRoomResponse } from "./create_room_response_pb";
import { file_create_room_response } from "./create_room_response_pb";
import type { JoinRoomRequest } from "./join_room_request_pb";
import { file_join_room_request } from "./join_room_request_pb";
import type { VoteRequest } from "./vote_request_pb";
import { file_vote_request } from "./vote_request_pb";
import type { RoomStateBroadcast } from "./room_state_broadcast_pb";
import { file_room_state_broadcast } from "./room_state_broadcast_pb";
import type { Error } from "./error_pb";
import { file_error } from "./error_pb";
import type { JoinRoomResponse } from "./join_room_response_pb";
import { file_join_room_response } from "./join_room_response_pb";
import type { VoteBroadcast } from "./vote_broadcast_pb";
import { file_vote_broadcast } from "./vote_broadcast_pb";
import type { MessageType } from "./base/message_type_pb";
import { file_base_message_type } from "./base/message_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file socket_message.proto.
 */
export const file_socket_message: GenFile = /*@__PURE__*/
  fileDesc("ChRzb2NrZXRfbWVzc2FnZS5wcm90bxIWcGxhbm5pbmdwb2tlci5yZWFsdGltZSLkBAoNU29ja2V0TWVzc2FnZRI2CgR0eXBlGAEgASgOMigucGxhbm5pbmdwb2tlci5yZWFsdGltZS5iYXNlLk1lc3NhZ2VUeXBlEi4KBWVycm9yGAIgASgLMh0ucGxhbm5pbmdwb2tlci5yZWFsdGltZS5FcnJvckgAEkYKEWNyZWF0ZVJvb21SZXF1ZXN0GAMgASgLMikucGxhbm5pbmdwb2tlci5yZWFsdGltZS5DcmVhdGVSb29tUmVxdWVzdEgAEkgKEmNyZWF0ZVJvb21SZXNwb25zZRgEIAEoCzIqLnBsYW5uaW5ncG9rZXIucmVhbHRpbWUuQ3JlYXRlUm9vbVJlc3BvbnNlSAASQgoPam9pblJvb21SZXF1ZXN0GAUgASgLMicucGxhbm5pbmdwb2tlci5yZWFsdGltZS5Kb2luUm9vbVJlcXVlc3RIABI6Cgt2b3RlUmVxdWVzdBgGIAEoCzIjLnBsYW5uaW5ncG9rZXIucmVhbHRpbWUuVm90ZVJlcXVlc3RIABJIChJyb29tU3RhdGVCcm9hZGNhc3QYByABKAsyKi5wbGFubmluZ3Bva2VyLnJlYWx0aW1lLlJvb21TdGF0ZUJyb2FkY2FzdEgAEkQKEGpvaW5Sb29tUmVzcG9uc2UYCCABKAsyKC5wbGFubmluZ3Bva2VyLnJlYWx0aW1lLkpvaW5Sb29tUmVzcG9uc2VIABI+Cg12b3RlQnJvYWRjYXN0GAkgASgLMiUucGxhbm5pbmdwb2tlci5yZWFsdGltZS5Wb3RlQnJvYWRjYXN0SABCCQoHY29udGVudEIlWiNwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZGlzdC1nb2IGcHJvdG8z", [file_create_room_request, file_create_room_response, file_join_room_request, file_vote_request, file_room_state_broadcast, file_error, file_join_room_response, file_vote_broadcast, file_base_message_type]);

/**
 * @generated from message planningpoker.realtime.SocketMessage
 */
export type SocketMessage = Message<"planningpoker.realtime.SocketMessage"> & {
  /**
   * @generated from field: planningpoker.realtime.base.MessageType type = 1;
   */
  type: MessageType;

  /**
   * @generated from oneof planningpoker.realtime.SocketMessage.content
   */
  content: {
    /**
     * @generated from field: planningpoker.realtime.Error error = 2;
     */
    value: Error;
    case: "error";
  } | {
    /**
     * @generated from field: planningpoker.realtime.CreateRoomRequest createRoomRequest = 3;
     */
    value: CreateRoomRequest;
    case: "createRoomRequest";
  } | {
    /**
     * @generated from field: planningpoker.realtime.CreateRoomResponse createRoomResponse = 4;
     */
    value: CreateRoomResponse;
    case: "createRoomResponse";
  } | {
    /**
     * @generated from field: planningpoker.realtime.JoinRoomRequest joinRoomRequest = 5;
     */
    value: JoinRoomRequest;
    case: "joinRoomRequest";
  } | {
    /**
     * @generated from field: planningpoker.realtime.VoteRequest voteRequest = 6;
     */
    value: VoteRequest;
    case: "voteRequest";
  } | {
    /**
     * @generated from field: planningpoker.realtime.RoomStateBroadcast roomStateBroadcast = 7;
     */
    value: RoomStateBroadcast;
    case: "roomStateBroadcast";
  } | {
    /**
     * @generated from field: planningpoker.realtime.JoinRoomResponse joinRoomResponse = 8;
     */
    value: JoinRoomResponse;
    case: "joinRoomResponse";
  } | {
    /**
     * @generated from field: planningpoker.realtime.VoteBroadcast voteBroadcast = 9;
     */
    value: VoteBroadcast;
    case: "voteBroadcast";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message planningpoker.realtime.SocketMessage.
 * Use `create(SocketMessageSchema)` to create a new message.
 */
export const SocketMessageSchema: GenMessage<SocketMessage> = /*@__PURE__*/
  messageDesc(file_socket_message, 0);

