// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file socket_message.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageType } from "./base/message_type_pb";
import { file_base_message_type } from "./base/message_type_pb";
import type { Error } from "./base/error_pb";
import { file_base_error } from "./base/error_pb";
import type { CreateRoomRequest } from "./create_room_request_pb";
import { file_create_room_request } from "./create_room_request_pb";
import type { CreateRoomResponse } from "./create_room_response_pb";
import { file_create_room_response } from "./create_room_response_pb";
import type { DisplayResultRequest } from "./display_result_request_pb";
import { file_display_result_request } from "./display_result_request_pb";
import type { JoinRoomRequest } from "./join_room_request_pb";
import { file_join_room_request } from "./join_room_request_pb";
import type { JoinRoomResponse } from "./join_room_response_pb";
import { file_join_room_response } from "./join_room_response_pb";
import type { RoomUpdateBroadcast } from "./room_update_broadcast_pb";
import { file_room_update_broadcast } from "./room_update_broadcast_pb";
import type { UserListBroadcast } from "./user_list_broadcast_pb";
import { file_user_list_broadcast } from "./user_list_broadcast_pb";
import type { VoteRequest } from "./vote_request_pb";
import { file_vote_request } from "./vote_request_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file socket_message.proto.
 */
export const file_socket_message: GenFile = /*@__PURE__*/
  fileDesc("ChRzb2NrZXRfbWVzc2FnZS5wcm90bxINcGxhbm5pbmdwb2tlciLqBAoNU29ja2V0TWVzc2FnZRIwCgdtc2dUeXBlGAEgASgOMh8ucGxhbm5pbmdwb2tlci5iYXNlLk1lc3NhZ2VUeXBlEioKBWVycm9yGAIgASgLMhkucGxhbm5pbmdwb2tlci5iYXNlLkVycm9ySAASPQoRY3JlYXRlUm9vbVJlcXVlc3QYAyABKAsyIC5wbGFubmluZ3Bva2VyLkNyZWF0ZVJvb21SZXF1ZXN0SAASPwoSY3JlYXRlUm9vbVJlc3BvbnNlGAQgASgLMiEucGxhbm5pbmdwb2tlci5DcmVhdGVSb29tUmVzcG9uc2VIABJDChRkaXNwbGF5UmVzdWx0UmVxdWVzdBgFIAEoCzIjLnBsYW5uaW5ncG9rZXIuRGlzcGxheVJlc3VsdFJlcXVlc3RIABI5Cg9qb2luUm9vbVJlcXVlc3QYBiABKAsyHi5wbGFubmluZ3Bva2VyLkpvaW5Sb29tUmVxdWVzdEgAEjsKEGpvaW5Sb29tUmVzcG9uc2UYByABKAsyHy5wbGFubmluZ3Bva2VyLkpvaW5Sb29tUmVzcG9uc2VIABJBChNyb29tVXBkYXRlQnJvYWRjYXN0GAggASgLMiIucGxhbm5pbmdwb2tlci5Sb29tVXBkYXRlQnJvYWRjYXN0SAASPQoRdXNlckxpc3RCcm9hZGNhc3QYCSABKAsyIC5wbGFubmluZ3Bva2VyLlVzZXJMaXN0QnJvYWRjYXN0SAASMQoLdm90ZVJlcXVlc3QYCiABKAsyGi5wbGFubmluZ3Bva2VyLlZvdGVSZXF1ZXN0SABCCQoHY29udGVudEIkWiJwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZG9tYWluYgZwcm90bzM", [file_base_message_type, file_base_error, file_create_room_request, file_create_room_response, file_display_result_request, file_join_room_request, file_join_room_response, file_room_update_broadcast, file_user_list_broadcast, file_vote_request]);

/**
 * @generated from message planningpoker.SocketMessage
 */
export type SocketMessage = Message<"planningpoker.SocketMessage"> & {
  /**
   * @generated from field: planningpoker.base.MessageType msgType = 1;
   */
  msgType: MessageType;

  /**
   * @generated from oneof planningpoker.SocketMessage.content
   */
  content: {
    /**
     * @generated from field: planningpoker.base.Error error = 2;
     */
    value: Error;
    case: "error";
  } | {
    /**
     * @generated from field: planningpoker.CreateRoomRequest createRoomRequest = 3;
     */
    value: CreateRoomRequest;
    case: "createRoomRequest";
  } | {
    /**
     * @generated from field: planningpoker.CreateRoomResponse createRoomResponse = 4;
     */
    value: CreateRoomResponse;
    case: "createRoomResponse";
  } | {
    /**
     * @generated from field: planningpoker.DisplayResultRequest displayResultRequest = 5;
     */
    value: DisplayResultRequest;
    case: "displayResultRequest";
  } | {
    /**
     * @generated from field: planningpoker.JoinRoomRequest joinRoomRequest = 6;
     */
    value: JoinRoomRequest;
    case: "joinRoomRequest";
  } | {
    /**
     * @generated from field: planningpoker.JoinRoomResponse joinRoomResponse = 7;
     */
    value: JoinRoomResponse;
    case: "joinRoomResponse";
  } | {
    /**
     * @generated from field: planningpoker.RoomUpdateBroadcast roomUpdateBroadcast = 8;
     */
    value: RoomUpdateBroadcast;
    case: "roomUpdateBroadcast";
  } | {
    /**
     * @generated from field: planningpoker.UserListBroadcast userListBroadcast = 9;
     */
    value: UserListBroadcast;
    case: "userListBroadcast";
  } | {
    /**
     * @generated from field: planningpoker.VoteRequest voteRequest = 10;
     */
    value: VoteRequest;
    case: "voteRequest";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message planningpoker.SocketMessage.
 * Use `create(SocketMessageSchema)` to create a new message.
 */
export const SocketMessageSchema: GenMessage<SocketMessage> = /*@__PURE__*/
  messageDesc(file_socket_message, 0);

