// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file user_list_broadcast.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { User } from "./base/user_pb";
import { file_base_user } from "./base/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user_list_broadcast.proto.
 */
export const file_user_list_broadcast: GenFile = /*@__PURE__*/
  fileDesc("Chl1c2VyX2xpc3RfYnJvYWRjYXN0LnByb3RvEhZwbGFubmluZ3Bva2VyLnJlYWx0aW1lIkUKEVVzZXJMaXN0QnJvYWRjYXN0EjAKBXVzZXJzGAEgAygLMiEucGxhbm5pbmdwb2tlci5yZWFsdGltZS5iYXNlLlVzZXJCJVojcGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2Rpc3QtZ29iBnByb3RvMw", [file_base_user]);

/**
 * @generated from message planningpoker.realtime.UserListBroadcast
 */
export type UserListBroadcast = Message<"planningpoker.realtime.UserListBroadcast"> & {
  /**
   * @generated from field: repeated planningpoker.realtime.base.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message planningpoker.realtime.UserListBroadcast.
 * Use `create(UserListBroadcastSchema)` to create a new message.
 */
export const UserListBroadcastSchema: GenMessage<UserListBroadcast> = /*@__PURE__*/
  messageDesc(file_user_list_broadcast, 0);

