// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file user_list_broadcast.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingUser } from "./base/voting_user_pb";
import { file_base_voting_user } from "./base/voting_user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user_list_broadcast.proto.
 */
export const file_user_list_broadcast: GenFile = /*@__PURE__*/
  fileDesc("Chl1c2VyX2xpc3RfYnJvYWRjYXN0LnByb3RvEg1wbGFubmluZ3Bva2VyIkIKEVVzZXJMaXN0QnJvYWRjYXN0Ei0KBXVzZXJzGAEgAygLMh4ucGxhbm5pbmdwb2tlci5iYXNlLlZvdGluZ1VzZXJCJFoicGxhbm5pbmdwb2tlci9kb21haW5fbW9kZWxzL2RvbWFpbmIGcHJvdG8z", [file_base_voting_user]);

/**
 * @generated from message planningpoker.UserListBroadcast
 */
export type UserListBroadcast = Message<"planningpoker.UserListBroadcast"> & {
  /**
   * @generated from field: repeated planningpoker.base.VotingUser users = 1;
   */
  users: VotingUser[];
};

/**
 * Describes the message planningpoker.UserListBroadcast.
 * Use `create(UserListBroadcastSchema)` to create a new message.
 */
export const UserListBroadcastSchema: GenMessage<UserListBroadcast> = /*@__PURE__*/
  messageDesc(file_user_list_broadcast, 0);

