// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file vote_request.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vote_request.proto.
 */
export const file_vote_request: GenFile = /*@__PURE__*/
  fileDesc("ChJ2b3RlX3JlcXVlc3QucHJvdG8SFnBsYW5uaW5ncG9rZXIucmVhbHRpbWUiGwoLVm90ZVJlcXVlc3QSDAoEdm90ZRgBIAEoCUIlWiNwbGFubmluZ3Bva2VyL2RvbWFpbl9tb2RlbHMvZGlzdC1nb2IGcHJvdG8z");

/**
 * @generated from message planningpoker.realtime.VoteRequest
 */
export type VoteRequest = Message<"planningpoker.realtime.VoteRequest"> & {
  /**
   * @generated from field: string vote = 1;
   */
  vote: string;
};

/**
 * Describes the message planningpoker.realtime.VoteRequest.
 * Use `create(VoteRequestSchema)` to create a new message.
 */
export const VoteRequestSchema: GenMessage<VoteRequest> = /*@__PURE__*/
  messageDesc(file_vote_request, 0);

