// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file vote_broadcast.proto (package planningpoker.realtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vote_broadcast.proto.
 */
export const file_vote_broadcast: GenFile = /*@__PURE__*/
  fileDesc("ChR2b3RlX2Jyb2FkY2FzdC5wcm90bxIWcGxhbm5pbmdwb2tlci5yZWFsdGltZSJ+Cg1Wb3RlQnJvYWRjYXN0Ej8KBXZvdGVzGAEgAygLMjAucGxhbm5pbmdwb2tlci5yZWFsdGltZS5Wb3RlQnJvYWRjYXN0LlZvdGVzRW50cnkaLAoKVm90ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQiVaI3BsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kaXN0LWdvYgZwcm90bzM");

/**
 * @generated from message planningpoker.realtime.VoteBroadcast
 */
export type VoteBroadcast = Message<"planningpoker.realtime.VoteBroadcast"> & {
  /**
   * @generated from field: map<string, string> votes = 1;
   */
  votes: { [key: string]: string };
};

/**
 * Describes the message planningpoker.realtime.VoteBroadcast.
 * Use `create(VoteBroadcastSchema)` to create a new message.
 */
export const VoteBroadcastSchema: GenMessage<VoteBroadcast> = /*@__PURE__*/
  messageDesc(file_vote_broadcast, 0);

