// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file vote_request.proto (package planningpoker, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VotingCard } from "./base/voting_card_pb";
import { file_base_voting_card } from "./base/voting_card_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vote_request.proto.
 */
export const file_vote_request: GenFile = /*@__PURE__*/
  fileDesc("ChJ2b3RlX3JlcXVlc3QucHJvdG8SDXBsYW5uaW5ncG9rZXIiOwoLVm90ZVJlcXVlc3QSLAoEdm90ZRgBIAEoCzIeLnBsYW5uaW5ncG9rZXIuYmFzZS5Wb3RpbmdDYXJkQiRaInBsYW5uaW5ncG9rZXIvZG9tYWluX21vZGVscy9kb21haW5iBnByb3RvMw", [file_base_voting_card]);

/**
 * @generated from message planningpoker.VoteRequest
 */
export type VoteRequest = Message<"planningpoker.VoteRequest"> & {
  /**
   * @generated from field: planningpoker.base.VotingCard vote = 1;
   */
  vote?: VotingCard;
};

/**
 * Describes the message planningpoker.VoteRequest.
 * Use `create(VoteRequestSchema)` to create a new message.
 */
export const VoteRequestSchema: GenMessage<VoteRequest> = /*@__PURE__*/
  messageDesc(file_vote_request, 0);

