// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: create_room_response.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	base "planningpoker/domain_models/domain/base"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *base.VotingRoom `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_room_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_room_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_create_room_response_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomResponse) GetRoom() *base.VotingRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_create_room_response_proto protoreflect.FileDescriptor

var file_create_room_response_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x6c,
	0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x16, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x72, 0x6f, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x56, 0x6f, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x42, 0x24, 0x5a,
	0x22, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_create_room_response_proto_rawDescOnce sync.Once
	file_create_room_response_proto_rawDescData = file_create_room_response_proto_rawDesc
)

func file_create_room_response_proto_rawDescGZIP() []byte {
	file_create_room_response_proto_rawDescOnce.Do(func() {
		file_create_room_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_create_room_response_proto_rawDescData)
	})
	return file_create_room_response_proto_rawDescData
}

var file_create_room_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_create_room_response_proto_goTypes = []any{
	(*CreateRoomResponse)(nil), // 0: planningpoker.CreateRoomResponse
	(*base.VotingRoom)(nil),    // 1: planningpoker.base.VotingRoom
}
var file_create_room_response_proto_depIdxs = []int32{
	1, // 0: planningpoker.CreateRoomResponse.room:type_name -> planningpoker.base.VotingRoom
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_create_room_response_proto_init() }
func file_create_room_response_proto_init() {
	if File_create_room_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_create_room_response_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_create_room_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_create_room_response_proto_goTypes,
		DependencyIndexes: file_create_room_response_proto_depIdxs,
		MessageInfos:      file_create_room_response_proto_msgTypes,
	}.Build()
	File_create_room_response_proto = out.File
	file_create_room_response_proto_rawDesc = nil
	file_create_room_response_proto_goTypes = nil
	file_create_room_response_proto_depIdxs = nil
}
