// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: join_room_response.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	base "planningpoker/domain_models/domain/base"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *base.VotingRoom `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	User *base.VotingUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_join_room_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_join_room_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_join_room_response_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRoomResponse) GetRoom() *base.VotingRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *JoinRoomResponse) GetUser() *base.VotingUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_join_room_response_proto protoreflect.FileDescriptor

var file_join_room_response_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x6c, 0x61, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x65, 0x2f,
	0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x10, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6c,
	0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f,
	0x6d, 0x12, 0x32, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x24, 0x5a, 0x22, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_join_room_response_proto_rawDescOnce sync.Once
	file_join_room_response_proto_rawDescData = file_join_room_response_proto_rawDesc
)

func file_join_room_response_proto_rawDescGZIP() []byte {
	file_join_room_response_proto_rawDescOnce.Do(func() {
		file_join_room_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_join_room_response_proto_rawDescData)
	})
	return file_join_room_response_proto_rawDescData
}

var file_join_room_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_join_room_response_proto_goTypes = []any{
	(*JoinRoomResponse)(nil), // 0: planningpoker.JoinRoomResponse
	(*base.VotingRoom)(nil),  // 1: planningpoker.base.VotingRoom
	(*base.VotingUser)(nil),  // 2: planningpoker.base.VotingUser
}
var file_join_room_response_proto_depIdxs = []int32{
	1, // 0: planningpoker.JoinRoomResponse.room:type_name -> planningpoker.base.VotingRoom
	2, // 1: planningpoker.JoinRoomResponse.user:type_name -> planningpoker.base.VotingUser
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_join_room_response_proto_init() }
func file_join_room_response_proto_init() {
	if File_join_room_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_join_room_response_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_join_room_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_join_room_response_proto_goTypes,
		DependencyIndexes: file_join_room_response_proto_depIdxs,
		MessageInfos:      file_join_room_response_proto_msgTypes,
	}.Build()
	File_join_room_response_proto = out.File
	file_join_room_response_proto_rawDesc = nil
	file_join_room_response_proto_goTypes = nil
	file_join_room_response_proto_depIdxs = nil
}
