// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: socket/join_room.proto

package socket

import (
	session "github.com/joelson-c/votecoms/session"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRoom struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token *session.Token         `protobuf:"bytes,1,opt,name=token"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_socket_join_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_socket_join_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JoinRoom) GetToken() *session.Token {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *JoinRoom) SetToken(v *session.Token) {
	x.xxx_hidden_Token = v
}

func (x *JoinRoom) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *JoinRoom) ClearToken() {
	x.xxx_hidden_Token = nil
}

type JoinRoom_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *session.Token
}

func (b0 JoinRoom_builder) Build() *JoinRoom {
	m0 := &JoinRoom{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

var File_socket_join_room_proto protoreflect.FileDescriptor

const file_socket_join_room_proto_rawDesc = "" +
	"\n" +
	"\x16socket/join_room.proto\x12\x06socket\x1a\x13session/token.proto\"0\n" +
	"\bJoinRoom\x12$\n" +
	"\x05token\x18\x01 \x01(\v2\x0e.session.TokenR\x05tokenB&Z$github.com/joelson-c/votecoms/socketb\beditionsp\xe8\a"

var file_socket_join_room_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_socket_join_room_proto_goTypes = []any{
	(*JoinRoom)(nil),      // 0: socket.JoinRoom
	(*session.Token)(nil), // 1: session.Token
}
var file_socket_join_room_proto_depIdxs = []int32{
	1, // 0: socket.JoinRoom.token:type_name -> session.Token
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_socket_join_room_proto_init() }
func file_socket_join_room_proto_init() {
	if File_socket_join_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_join_room_proto_rawDesc), len(file_socket_join_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socket_join_room_proto_goTypes,
		DependencyIndexes: file_socket_join_room_proto_depIdxs,
		MessageInfos:      file_socket_join_room_proto_msgTypes,
	}.Build()
	File_socket_join_room_proto = out.File
	file_socket_join_room_proto_goTypes = nil
	file_socket_join_room_proto_depIdxs = nil
}
