// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: socket/socket.proto

package socket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Socket struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message isSocket_Message       `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Socket) Reset() {
	*x = Socket{}
	mi := &file_socket_socket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socket) ProtoMessage() {}

func (x *Socket) ProtoReflect() protoreflect.Message {
	mi := &file_socket_socket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Socket) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*socket_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Socket) SetJoinRoom(v *JoinRoom) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &socket_JoinRoom{v}
}

func (x *Socket) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *Socket) HasJoinRoom() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*socket_JoinRoom)
	return ok
}

func (x *Socket) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *Socket) ClearJoinRoom() {
	if _, ok := x.xxx_hidden_Message.(*socket_JoinRoom); ok {
		x.xxx_hidden_Message = nil
	}
}

const Socket_Message_not_set_case case_Socket_Message = 0
const Socket_JoinRoom_case case_Socket_Message = 1

func (x *Socket) WhichMessage() case_Socket_Message {
	if x == nil {
		return Socket_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *socket_JoinRoom:
		return Socket_JoinRoom_case
	default:
		return Socket_Message_not_set_case
	}
}

type Socket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	JoinRoom *JoinRoom
	// -- end of xxx_hidden_Message
}

func (b0 Socket_builder) Build() *Socket {
	m0 := &Socket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.JoinRoom != nil {
		x.xxx_hidden_Message = &socket_JoinRoom{b.JoinRoom}
	}
	return m0
}

type case_Socket_Message protoreflect.FieldNumber

func (x case_Socket_Message) String() string {
	md := file_socket_socket_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSocket_Message interface {
	isSocket_Message()
}

type socket_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,1,opt,name=join_room,json=joinRoom,oneof"`
}

func (*socket_JoinRoom) isSocket_Message() {}

var File_socket_socket_proto protoreflect.FileDescriptor

const file_socket_socket_proto_rawDesc = "" +
	"\n" +
	"\x13socket/socket.proto\x12\x06socket\x1a\x16socket/join_room.proto\"D\n" +
	"\x06Socket\x12/\n" +
	"\tjoin_room\x18\x01 \x01(\v2\x10.socket.JoinRoomH\x00R\bjoinRoomB\t\n" +
	"\amessageB&Z$github.com/joelson-c/votecoms/socketb\beditionsp\xe8\a"

var file_socket_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_socket_socket_proto_goTypes = []any{
	(*Socket)(nil),   // 0: socket.Socket
	(*JoinRoom)(nil), // 1: socket.JoinRoom
}
var file_socket_socket_proto_depIdxs = []int32{
	1, // 0: socket.Socket.join_room:type_name -> socket.JoinRoom
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_socket_socket_proto_init() }
func file_socket_socket_proto_init() {
	if File_socket_socket_proto != nil {
		return
	}
	file_socket_join_room_proto_init()
	file_socket_socket_proto_msgTypes[0].OneofWrappers = []any{
		(*socket_JoinRoom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_socket_proto_rawDesc), len(file_socket_socket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socket_socket_proto_goTypes,
		DependencyIndexes: file_socket_socket_proto_depIdxs,
		MessageInfos:      file_socket_socket_proto_msgTypes,
	}.Build()
	File_socket_socket_proto = out.File
	file_socket_socket_proto_goTypes = nil
	file_socket_socket_proto_depIdxs = nil
}
