name: Deploy back-end to ECR

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

env:
  ROLE_TO_ASSUME: ${{ secrets.PROD_AWS_ROLE_TO_ASSUME }}
  AWS_REGION: ${{ vars.PROD_AWS_REGION }}
  DEPLOYMENT_GROUP: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment --application-name ${{ vars.DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --github-location repository=${{ github.repository }},commitId=$(git rev-parse HEAD) \
            --ignore-application-stop-failures
